#!/bin/sh
FILES=$(git diff --cached --name-only --diff-filter=ACMR | sed 's| |\\ |g')
[ -z "$FILES" ] && exit 0

# Lint all selected files

# Get only files that are in src
SRC_FILES=$(echo "$FILES" | grep "^src/")

echo "$SRC_FILES" | xargs yarn lint

# Prettify all selected files
echo "$FILES" | xargs yarn prettier

# Add back the modified files to staging
echo "$FILES" | xargs git add

exit 0